name: Build cargo

on:
  workflow_dispatch:

jobs:
  #
  Build-cargo:
    name: Build cargo
    runs-on: parity-default
    container:
      image: docker.io/paritypr/ci-unified:staging-bullseye-1.88.0-v202507111614
    services:
      minio:
        image: bitnami/minio:2024.5.7
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: rootroot
          MINIO_DEFAULT_BUCKETS: forklift:public
        ports:
          - 9000:9000

    steps:
      - name: Checkout cargo 1
        uses: actions/checkout@v4
        with:
          repository: rust-lang/cargo
          ref: rust-1.88.0

      - run: |
          mkdir .forklift
          cat >.forklift/config.toml <<EOL
          [general]
            logLevel = "debug"
            threadsCount = 3
          [compression]
            type = "none"
          [storage]
            type = "s3"
          [storage.s3]
            endpointUrl = "http://minio:9000"
            bucketName = "forklift"
            useSSL = false
          [cache.extraMetadata]
            github_run_id="$GITHUB_RUN_ID"
            github_job="$GITHUB_JOB"

          [metrics]
            enabled = true
            pushEndpoint = "assdfgh"

          [metrics.extraLabels]
            environment = "production"
            job_name = "$GITHUB_JOB"
            project_name = "$GITHUB_REPOSITORY"
          EOL

      - name: build cargo
        run: forklift cargo build --release