name: gha runners test

on:
  workflow_dispatch:


jobs:
  prom-internal-service:
    runs-on: parity-default
    steps:
      - name: curl
        run: curl --connect-timeout 20 http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write

  alloy-internal-service:
    runs-on: parity-default
    steps:
      - name: curl
        run: curl --connect-timeout 20 http://alloy-forwarder-stg.alloy:8080/api/v1/metrics/write

  homedir:
    runs-on: parity-default
    container:
      image: docker.io/paritytech/ci-unified:bullseye-1.88.0-2025-06-27-v202507101316
    steps:
      - name: echo
        run: echo $HOME
