name: test

on:
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job1
      - name: Set changes
        id: set_changes
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            rust:
              - '**/*'
              - '!.github/**/*'
              - '!prdoc/**/*'
              - '!docs/**/*'
            currentWorkflow:
              - '${{ steps.current_file.outputs.currentWorkflowFile }}'
              - '.github/workflows/reusable-preflight.yml'

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 20s
      - run: echo job2

  job3:
    runs-on: cattery-gce
    steps:
      - run: sleep 20s
      - run: echo job3

  job4:
    runs-on: cattery-gce
    steps:
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Display Go version
        run: go version

