name: test

on:
  push:
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job1

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 20s
      - run: echo job2