name: cattery test docker local

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  job3:
    runs-on: cattery-docker-local
    steps:
      - run: sleep 20s
      - run: echo job3

  job4:
    runs-on: cattery-docker-local
    steps:
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Display Go version
        run: go version

      - uses: actions/checkout@v4
        with:
          repository: paritytech/cattery

      - run: go build -C src -o ../cattery

      - run: ./cattery --help

  matrix-job:
    runs-on: cattery-docker-local
    strategy:
      fail-fast: false
      matrix:
        partition: [1,2,3,4,5,6,7,8,9]
    steps:
      - run: echo ${{ matrix.partition }}
      - run: sleep 20s